Use `jsonb` data type for PostgresSQL to increase perfomance
statamic/eloquent-driver pull request #82
Opened 2022-10-25 08:06 UTC by helloiamlukas

To improve perfomance for Postgres databases, the `json` columns can use the `jsonb` data type.

This is will reduce responsetimes drastically when dealing with large datasets.

2022-10-26 18:39 UTC, jasonvarga requested changes
I'm fairly sure you can just to `$table->jsonb('name')` without all those conditions.

On DBs that don't support jsonb, it'll fall back to json or text.

Postgres uses `jsonb` as expected:

https://github.com/laravel/framework/blob/ec3958de050d14f15832aa7604fb6834efa807bf/src/Illuminate/Database/Schema/Grammars/PostgresGrammar.php#L780-L783


MySQL goes to `json`:

https://github.com/laravel/framework/blob/ec3958de050d14f15832aa7604fb6834efa807bf/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L718-L721

SQLite goes to `text`:

https://github.com/laravel/framework/blob/ec3958de050d14f15832aa7604fb6834efa807bf/src/Illuminate/Database/Schema/Grammars/SQLiteGrammar.php#L624-L633

2022-11-07 16:29 UTC, helloiamlukas commented
Yes, you are right. I removed them now. Thanks for the hint!

2022-11-07 20:31 UTC, jasonvarga commented on database/migrations/create_navigations_table.php.stub
> +            $table->string('locale')->nullable()->index();
What's this `locale` column?

2022-11-09 21:39 UTC, jasonvarga approved these changes

2022-11-09 21:41 UTC, merged